controller_server:
  ros__parameters:
    controller_frequency: 30.0
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 25
      model_dt: 0.05   # Hz at 20 
      batch_size: 2000
      vx_std: 0.7 # standard deviation for x
      vy_std: 0.0 # irrelevant
      wz_std: 0.7
      vx_max: 2.0 # as max is 5mph, kept this as 2.23 m/s
      vx_min: -0.25 # even though the minimum is 1 kmph, kept it -ve (default val) to allow backup
      vy_max: 0.0   # irrelevant
      wz_max: 1.8
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.5
      temperature: 0.1 # how greedy the planner is, closer to 0 more greedy
      gamma: 0.015  # idk
      motion_model: "DiffDrive"
      visualize: false #not needed  
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "TwirlingCritic"]
      
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0
        threshold_to_consider: 0.5

      ObstaclesCritic:
        enabled: true
        cost_power: 1
        consider_footprint: true
        repulsion_weight: 12.0
        critical_weight: 20.0
        collision_cost: 10000.0
        collision_margin_distance: 0.15
        near_goal_distance: 0.1

      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        critical_cost: 30.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 3
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 12.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        forward_preference: true

      # VelocityDeadbandCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 35.0
      #   deadband_velocities: [0.05, 0.05, 0.05]

      TwirlingCritic:
        enabled: true
        twirling_cost_power: 2
        twirling_cost_weight: 5.0
 
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.1
      #robot_radius: 0.554
      footprint: "[[0.5, 0.42], [0.5, -0.42], [-0.5, -0.42], [-0.5, 0.42]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        map_topic: /map
        enabled: true
        subscribe_to_updates: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7
        cost_scaling_factor: 10.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true           
  local_costmap_client:
    ros__parameters:
      use_sim_time: true
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: true

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      #robot_radius: 0.554
      footprint: "[[0.5, 0.42], [0.5, -0.42], [-0.5, -0.42], [-0.5, 0.42]]"
      resolution: 0.1
      track_unknown_space: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true        
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        map_topic: /map
        enabled: true
        subscribe_to_updates: true   
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 1.0
        always_send_full_costmap: true
  global_costmap_client:
    ros__parameters:
      use_sim_time: true
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: true
  
velocity_smoother:        
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 30.0    
    max_velocity: [2.5, 0.0, 7.0]
    max_accel: [3.0, 0.0, 4.0]
    max_decel: [-3.0, 0.0, -7.0]
